name: Docker Image Publish

on:
  push:
    branches: [ 'dev' ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker Dev image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags : type=raw,latest-dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
